name: Self-hosted CI
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-prerequisites:
    name: Check prerequisites
    runs-on: [self-hosted, kmc]
    env:
      DATA_DIR: ../../../../data
      SCRIPT: tests/kmc_CLI/check-prerequisites.py
    steps:
    - name: Check prerequisites
      run: |
        chmod +x $SCRIPT
        /usr/bin/time -v $SCRIPT $DATA_DIR

  prepare-small-fastq-tests:
    name: Prepare small fastq tests
    runs-on: [self-hosted, kmc]
    env:      
      TRIVIAL_COUNTER: tests/kmc_CLI/trivial-k-mer-counter/bin/counter
      DATA_DIR: ../../../../data
      SCRIPT: tests/kmc_CLI/prepare_small_fastq_tests.py
      FILE_TO_GET_PART_FROM: F.vesca/SRR072005.fastq.gz
    steps:      
    - name: Compile trivial counter
      run: |
        (cd tests/kmc_CLI/trivial-k-mer-counter; /usr/bin/time -v make)
    - name: Prepare pattern data
      run: |
        chmod +x $SCRIPT
        /usr/bin/time -v $SCRIPT $DATA_DIR $TRIVIAL_COUNTER $FILE_TO_GET_PART_FROM 400000

  make-tests:
    name: Make tests
    runs-on: [self-hosted, kmc]
    needs: check-prerequisites
    env: 
      KMC_EXE: ./bin/kmc
      KMC_DUMP_EXE: ./bin/kmc_dump
      KMC_TOOLS: ./bin/kmc_tools
    steps:
    - uses: actions/checkout@v2
    - name: make (default)
      run: |
        /usr/bin/time -v make -j32

  small-fastq-tests:
    name: Small fastq tests
    runs-on: [self-hosted, kmc]
    needs: [make-tests, prepare-small-fastq-tests]
    env:      
      DATA_DIR: ../../../../data
      SCRIPT: tests/kmc_CLI/run_small_fastq_tests.py
      KMC_EXE: ./bin/kmc
      KMC_DUMP_EXE: ./bin/kmc_dump
      KMC_TOOLS: ./bin/kmc_tools

    steps:
    - name: Run all small fastq tests
      run: |
        chmod +x $SCRIPT
        /usr/bin/time -v $SCRIPT $DATA_DIR $KMC_EXE $KMC_TOOLS $KMC_DUMP_EXE
   






  